/**
 * Single source of truth for all invoke-able IPC channels.
 *
 * Consumed by:
 * - `ipc.ts` to derive the `IpcChannel` union type
 * - `main/ipc/registry.ts` for unregistration on shutdown
 * - `preload/index.ts` for the invoke allowlist
 *
 * Adding an IPC operation = add the channel here, then its contract in `ipc.ts`,
 * validator in `validate.ts`, allowlist handler in preload, and handler in registry.
 */
export const IPC_CHANNELS = [
  'profiles:list',
  'profiles:get',
  'profiles:create',
  'profiles:update',
  'profiles:remove',
  'connection:connect',
  'connection:disconnect',
  'connection:test',
  'connection:getState',
  'connection:hostKeyResponse',
  'terminal:open',
  'terminal:write',
  'terminal:resize',
  'terminal:close',
  'docker:isAvailable',
  'docker:listContainers',
  'docker:listImages',
  'docker:listVolumes',
  'docker:listNetworks',
  'docker:startContainer',
  'docker:stopContainer',
  'docker:restartContainer',
  'docker:removeContainer',
  'docker:inspectContainer',
  'docker:removeImage',
  'docker:removeVolume',
  'docker:logsStart',
  'docker:logsStop',
  'ports:list',
  'ports:setFirewallRule',
  'ports:deleteFirewallRule',
  'nginx:status',
  'nginx:configTree',
  'nginx:readConfig',
  'nginx:writeConfig',
  'nginx:validate',
  'nginx:action',
  'nginx:logPaths',
  'nginx:logsStart',
  'nginx:logsStop',
  'ssl:overview',
  'ssl:certificate',
  'ssl:nginxSites',
  'ssl:installCertbot',
  'ssl:enableHttpsStart',
  'ssl:enableHttpsCancel',
  'ssl:renew',
  'ssl:testRenewal',
  'ssl:enableAutoRenewal',
  'ssl:verifyHttps',
  'ssl:renewalLog',
  'files:list',
  'files:read',
  'files:write',
  'files:mkdir',
  'files:rename',
  'files:delete',
  'files:upload',
  'files:download',
  'files:copy',
  'files:cancelTransfer',
  'logs:start',
  'logs:stop',
  'logs:setFilters',
  'stats:getInfo',
  'stats:subscribe',
  'stats:unsubscribe',
  'services:isAvailable',
  'services:list',
  'services:getUnit',
  'services:getUnitFile',
  'services:getUnitLogs',
  'services:action',
  'cron:list',
  'cron:getSource',
  'cron:createJob',
  'cron:updateJob',
  'cron:deleteJob',
  'users:isAvailable',
  'users:list',
  'users:get',
  'users:groups',
  'users:action',
  'processes:list',
  'processes:get',
  'processes:subscribe',
  'processes:unsubscribe',
  'processes:signal',
  'packages:isAvailable',
  'packages:overview',
  'packages:list',
  'packages:search',
  'packages:info',
  'packages:updates',
  'packages:operationStart',
  'packages:operationCancel',
  'deployments:scan',
  'deployments:getSnapshot',
  'deployments:lookup',
  'deployments:historyList',
  'deployments:tag',
  'deployments:tagCurrent',
  'deployments:diff',
  'deployments:snapshotDiff',
  'deployments:deploymentHistory',
  'window:toggleMaximize',
  'window:isFullscreen'
] as const

export type IpcChannel = (typeof IPC_CHANNELS)[number]

export const IPC_EVENTS = [
  'connection:stateChanged',
  'connection:hostKeyPrompt',
  'terminal:data',
  'terminal:exit',
  'logs:entries',
  'logs:status',
  'stats:update',
  'processes:update',
  'packages:operationStep',
  'packages:operationOutput',
  'packages:operationDone',
  'files:transferProgress',
  'files:transferComplete',
  'docker:logsData',
  'docker:logsExit',
  'nginx:logsData',
  'nginx:logsExit',
  'ssl:workflowStep',
  'ssl:workflowOutput',
  'ssl:workflowDone',
  'window:fullscreenChanged',
  'deployments:scanProgress'
] as const

export type IpcEvent = (typeof IPC_EVENTS)[number]
